### PR TITLE
Workarounding with envvars

### PR DESCRIPTION
**Pull request by gfleury**
Workaround to #2

### CODE REVIEW

**Comment by jfroche** [comment]
Great, it works for us. We may want to prefix the environment variables with `GOBBS_` to prevent confusion ?

**Comment by gfleury** [comment]
Great!
The prefix idea is great, but I can do it over the weekend, if you are in a hurry you can take over here and we do the merge after.

**Comment by jfroche** [comment]
Can you merge it in master ?

**Comment by gfleury** [comment]
Oh, my mistake.

**Comment by gfleury** [comment]
Fixes #2

**Pull request merged**
